export const MESSAGES = {
  AUTH: {
    UNAUTHENTICATED: "Username or password is incorrect",
    AUTHENTICATED: "Authenticated successfully",
    USERNAME_INVALID: "Username is required",
    PASSWORD_INVALID: "Password is required",
    PASSWORD_TOO_SHORT: "Password must be at least 6 characters long",
    NAME_INVALID: "Name is required",
    NAME_TOO_SHORT: "Name must be at least 2 characters long",
    EMAIL_INVALID: "Email is required",
    EMAIL_INVALID_FORMAT: "Email is invalid",
    PHONE_INVALID: "Phone is required",
    PHONE_INVALID_FORMAT: "Phone is invalid",
    CONFIRM_PASSWORD_INVALID: "Confirm password is required",
    CONFIRM_PASSWORD_MISMATCH: "Confirm password does not match",
    REGISTER_SUCCESS:
      "Register successfully. please check your email to activate your account",
    REGISTER_FAILED: "Register failed",
    REGISTER_VALIDATE_FAILED: "Please fill all the fields",
    ACTIVE_ACCOUNT_FAILED: "Active account failed",
    RESET_PASSWORD_VALIDATE_FAILED: "Please fill Password and Confirm Password",
    RESET_PASSWORD_SUCCESS: "Reset password successfully",
    RESET_PASSWORD_FAILED: "Reset password failed",
  },
};
